spring:
  application:
    name: user

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    encoding: UTF-8
    basename: messages

  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    locale-resolver: accept-header

  servlet:
    multipart:
      max-file-size: 3500MB
      max-request-size: 3500MB
      enabled: true
    encoding:
      charset: UTF-8

  kafka:
    bootstrap-servers: localhost:9092

server:
  tomcat:
    response-character-encoding: UTF-8
    request-character-encoding: UTF-8
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
  port: 8001

slay:
  app:
    secret: ${APP_SECRET}
    lifetime: 600000000
    httpprotocol: ${HTTP_PROTOCOL}
    domain: ${DOMAIN}

storage:
  location: /app/uploads

course:
  service:
    url: http://localhost:8080

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
    instances:
      user-service:
        baseConfig: default