server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user:8001
          predicates:
            - Path=/api/auth/**, /api/user/**, /api/chat/**

        - id: course-service
          uri: http://course:8002
          predicates:
            - Path=/api/training-course/**, /api/category/**
      
        - id: support-service
          uri: http://support:8003
          predicates:
            - Path=/api/support/**

        - id: complaint-service
          uri: http://complaint:8004
          predicates:
            - Path=/api/complaint/**, /api/complaint-course/**, /api/complaint-user/**

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /api/auth/v3/api-docs
      - name: course-service
        url: /api/training-course/v3/api-docs
      - name: complaint-service
        url: /api/complaint/v3/api-docs
      - name: support-service
        url: /api/support/v3/api-docs
      - name: notification-service
        url: /api/notification/v3/api-docs
    path: /swagger-ui.html
    api-docs:
      enabled: true
      version: openapi_3_0
      groups:
        enabled: true