spring.application.name=notification

server.port=8000

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.notification.group-id=forgot-password-notification-group
spring.kafka.consumer.notification.auto-offset-reset=earliest

spring.kafka.consumer.birthday.group-id=birthday-notification-group
spring.kafka.consumer.birthday.auto-offset-reset=earliest

spring.mail.host=smtp.timeweb.ru
spring.mail.port=465
spring.mail.username=noreply@slaygym.ru
spring.mail.password=g5qdo6gd40
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false