version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - demo_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://demo_db:5432/Slay?useSSL=false&serverTimezone=UTC'
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  demo_db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Slay
    volumes:
      - pg_demo:/data/postgres
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  redis_data:
  pg_demo: